---
title: "GAM"
output: html_document
date: "2022-11-21"
---

```{r}
head(data)

trainIndex <- c(seq(1, 0.8*nrow(data)))
testIndex <- c(seq(0.8*nrow(data) + 1, nrow(data)))

train  <- data[trainIndex, ]
test   <- data[testIndex, ]
```

```{r}
library("mgcv")
gam.fit = gam(totalTrips ~ temp + totalCrimes + humidity + windspeed + visibility + feelslike + uvindex, data = train)
summary(gam.fit)

gam.fit.smoothing = gam(totalTrips ~ temp + totalCrimes + humidity + windspeed + visibility + feelslike + uvindex, data = train)
summary(gam.fit.smoothing)
```

```{r}
gam.fit.sse =sum(fitted(gam.fit) - train$totalTrips)^2
gam.fit.ssr =sum(fitted(gam.fit) -mean(train$totalTrips))^2
gam.fit.rSquare = 1 - (gam.fit.sse /(gam.fit.ssr + gam.fit.sse))
cat("The R square GAM is: %s", gam.fit.rSquare)

gam.fit.smoothing.sse =sum(fitted(gam.fit.smoothing) - train$totalTrips)^2
gam.fit.smoothing.ssr =sum(fitted(gam.fit.smoothing) -mean(train$totalTrips))^2
gam.fit.smoothing.rSquare = 1 - (gam.fit.smoothing.sse /(gam.fit.smoothing.ssr + gam.fit.smoothing.sse))
cat("The R square GAM is: %s", gam.fit.smoothing.rSquare)
```


```{r}
library("ggplot2")
predicted = predict(gam.fit, newdata = test)
predicted

plot = data.frame(test$date, test$totalTrips, predicted)
plot

head(plot)
ggp = ggplot(data = plot) + 
  geom_line(aes(x = test.date, y = test.totalTrips), color = 'red') + 
  geom_line(aes(x = test.date, y = predicted), color = 'green')
ggp
```

_*Using Cross Validation over here. The initial Window will be of length 500 and test will be of 100*_
```{r}

library(tidyverse)
library(caret)
library(doParallel)

set.seed(123)
seeds <- vector(mode = "list", length = 1809)
for(i in 1:1809) seeds[[i]] <- sample.int(1000, 5, replace = FALSE)
registerDoParallel(cores=3)

myTimeControl <- trainControl(method = "timeslice",
                              initialWindow = 500,
                              horizon = 100,
                              fixedWindow = FALSE,
                              allowParallel = TRUE,
                              seeds = seeds)

```


_*Regularized Linear Regression*_
```{r}
tuneLength.num <- 5

glmnet.mod <- train(totalTrips ~ temp + totalCrimes + humidity + windspeed + visibility + feelslike + uvindex,
                    data = train,
                    method = "glmnet",
                    family = "gaussian",
                    trControl = myTimeControl,
                    tuneLength=tuneLength.num,
                    metric='RMSE'
                )
summary(glmnet.mod)
```

_*Training the Gam Model.*_
```{r}
train
gam.mod <- train(totalTrips ~ temp + totalCrimes + humidity + windspeed + visibility + feelslike + uvindex,
                   data = train,
                   method = "gam",
                   trControl = myTimeControl,
                   tuneLength=tuneLength.num,
                   metric='RMSE'
                 )
```


_* Comparing the models over here.*_
```{r}
resamps <- resamples(list(glmnet = glmnet.mod, gam=gam.mod))
ss <- summary(resamps)
knitr::kable(ss[[3]]$RMSE)
```

