Code

```{r}
rm(list = ls())
rows = c("tripduration", "starttime", "stoptime", "start.station.id", "start.station.name", "start.station.latitude", "start.station.longitude", "end.station.id", "end.station.name", "end.station.latitude", "end.station.longitude", "bikeid", "usertype")
tripData = data.frame()
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2015-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2016-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2017-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2018-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2019-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2020-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2021-tripdata.csv")[rows])
tripData = rbind(tripData, read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/dipen/2022-tripdata.csv")[rows])
head(tripData)
```

```{r}
library(dplyr)
tripData$date = as.Date(tripData$starttime, "%Y-%m-%d")

numberOfTrips = tripData %>% group_by(date) %>% 
  summarise(totalTrips=length(bikeid),
            .groups = 'drop')
numberOfTrips
```


```{r}
holiday_data = read.csv("/Users/dipenchawla/Desktop/DIPEN_DPA/Project/holidays.csv")
holiday_data$Date = as.Date(holiday_data$Date, "%Y-%m-%d")
merged_data = merge(numberOfTrips, holiday_data, by.x = "totalTrips", by.y ="Date")
merged_data
```