---
title: "LinearModel"
output: html_document
date: "2022-11-20"
---

```{r}
head(data)

trainIndex <- c(seq(1, 0.8*nrow(data)))
testIndex <- c(seq(0.8*nrow(data) + 1, nrow(data)))

train  <- data[trainIndex, ]
test   <- data[testIndex, ]

lm.fit = lm(data = train, totalTrips ~ temp + totalCrimes + humidity + windspeed + visibility + 
    feelslike + uvindex)
summary(lm.fit)
```

```{r}
library("ggplot2")
lm.predict = predict(lm.fit, newdata = test)
lm.predict

plot = data.frame(test$date, test$totalTrips, lm.predict)
plot

head(plot)
ggp = ggplot(data = plot) + 
  geom_line(aes(x = test.date, y = test.totalTrips), color = 'red') + 
  geom_line(aes(x = test.date, y = lm.predict), color = 'green')
ggp
```

***As we are going to predict the next total trips. We will be working on time series data, for that we can't perform k - fold cross validation and temporal ordreing will be out of order.***
```{r}
library(tidyverse)
library(lubridate)
library(caret)
library(doParallel)
library(lattice)
library(pdp)

knitr::kable(head(data))
knitr::kable(tail(data))
```

```{r}

```

